### ISSUE TITLE
[Client] Banner Component

### ISSUE THREAD

**Issue by Seulji-jo** [codestates/Netfreview-client#121]
### ISSUE
- Group:   `client`
- Type: `feature`
- Detail: create Banner component

### TODO
1. [x]Create the skeleton of the Banner component
2. [x] Create CSS of Banner component
3. [x] Feature of Banner component

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
