### ISSUE TITLE
[Client] Feature - UserPage and API

### ISSUE THREAD

**Issue by Seulji-jo** [codestates/Netfreview-client#122]
### ISSUE
- Group:   `client`
- Type: `feature`
- Detail: create Banner component

### TODO
1. [x] 기존 유저페이지에서 마이페이지로 변경
2. [x] MyInfo API (기존에 있던 UserInfo API에서 변경)
2. [x] 유저페이지생성: 다른 유저페이지
3. [x] UserInfo API (기존에 있던 UserInfo API에서 변경)

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
