### ISSUE TITLE
[Client] feature&API - 이거어때Modal

### ISSUE THREAD

**Issue by choijw1116** [codestates/Netfreview-client#34]
### ISSUE
- Group: `client`
- Type: `feature`
- Detail: create feature&API of Mainpage

### TODO
1. [x] 포스터클릭시, reviewpage로 이동
2. [x] 모달창 X버튼누르면, 이전페이지로 이동
3. [x] 이거어때page로 서버에서 video list 가져오기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
