### ISSUE TITLE
[Client] feature&API - SearchPage

### ISSUE THREAD

**Issue by choijw1116** [codestates/Netfreview-client#37]
### ISSUE
- Group:   `client`
- Type: `feature`
- Detail: create feature&API SearchPage component

### TODO
1. [] 메인페이지에서 검색어입력후, 돋보기를 누르면, SearchPage로 이동
2. [] data가 있으면, 포스터가 rendering
3. [] data가 null이면, 없음 페이지로 이동
4. [] 포스터를 클릭하면, reviewpage로 이동
5. [] searchpage로 서버에서 video list 가져오기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__2__`
- Urgency: `High`
